name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish Windows
      run: dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true
    - name: Publish Windows
      uses: actions/release
      with:
        os: win-x64
    - name: Publish OSX
      uses: actions/release
      with:
        os: osx-x64
    - name: Publish Linux
      uses: actions/release
      with:
        os: linux-x64
