name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish Windows
      run: |
          rm AgileBot.exe
          dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true
          mv bin/Release/netcoreapp3.1/win-x64/AgileBot.exe ./AgileBot.exe
    - name: Upload Windows
      uses: actions/upload-artifact@v2
      with:
        name: build-with-settings
        path: | 
          AgileBot.exe
          settings.json.example
    - name: Publish OSX
      run: |
          rm AgileBot.exe
          dotnet publish -c Release -r osx-x64 -p:PublishSingleFile=true
          mv bin/Release/netcoreapp3.1/osx-x64/AgileBot.exe ./AgileBot.exe
    - name: Upload OSX
      uses: actions/upload-artifact@v2
      with:
        name: build-with-settings
        path: | 
          AgileBot.exe
          settings.json.example
    - name: Publish Linux
      run: |
          rm AgileBot.exe
          dotnet publish -c Release -r linux-x64 -p:PublishSingleFile=true
          mv bin/Release/netcoreapp3.1/linux-x64/AgileBot.exe ./AgileBot.exe
    - name: Upload Linux
      uses: actions/upload-artifact@v2
      with:
        name: build-with-settings
        path: | 
          AgileBot.exe
          settings.json.example
