inputs:
  os: 
    description: 'OS type: win-x64, osx-x64, or linux-x64'
runs:
  using: "composite"
  steps: 
  - name: Build ${{ inputs.os }}
    run: dotnet publish -c Release -r ${{ inputs.os }} -p:PublishSingleFile=true
    run: cp settings.json.example bin/Release/netcoreapp3.1/${{ inputs.os }}/settings.json.example
    run: cd bin/Release/netcoreapp3.1/${{ inputs.os }}
    uses: actions/upload-artifact@v2
    with:
        name: build-with-settings
        path: | 
          AgileBot.exe
          settings.json.example